version: "3"
services:
  nginx:
    image: "nginx"
    volumes:
      - ./nginx-config:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
  dwf-form:
    #image: "dwf-form"
    build: ../webform
    expose:
      - 3000
    environment:
      - SESSION_KEY
      - GH_CLIENT_ID
      - GH_TOKEN
      - GH_OAUTH_SECRET
      - GH_REPO
      - GH_USERNAME
  dwf-bot:
    #image: "dwf-form"
    build: ../dwf-bot
    environment:
      - SESSION_KEY
      - GH_CLIENT_ID
      - GH_TOKEN
      - GH_USERNAME
      - GH_REPO
    restart: always
